title: "Chris Oliver"
name: "Chris Oliver"
description: "Postdoc in open quantum systems"
url: "https://chroli1.github.io"
baseurl: ""
repository: "chroli1/chroli1.github.io"

plugins:
  - jekyll-scholar
  - jemoji

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

permalink: /:categories/:title/

include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

author:
  name: "Chris Oliver"
  avatar: "/images/profile.jpg"
  bio: "Postdoc in open quantum systems"
  location: "Glasgow, UK :scotland:"
  employer: "University of Strathclyde"
  email: "christopher.oliver AT strath.ac.uk"
  googlescholar: https://scholar.google.com/citations?user=4Mzopb4AAAAJ&hl=en
  orcid: https://orcid.org/0009-0003-3135-5592
  linkedin: https://www.linkedin.com/in/chris-oliver-a537181ab/
  github: https://github.com/chroli1

collections:
  talks:
    output: true
    permalink: /talks/:path/
  projects:
    output: true
    permalink: /projects/:path/
  blackboard:
    output: true
    permalink: /blackboard/:path/

scholar:
  style: apa
  source: _bibliography
  bibliography: papers.bib
  bibliography_template: bib
  sort_by: year
  order: descending

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: blackboard
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: other-stuff
    values:
      layout: single
      author_profile: true
